### PR TITLE
Adds options for repeating a run and grouping tests

### PR DESCRIPTION
**Pull request by fschulze**

### CODE REVIEW

**Comment by klrmn** [comment]
Hi @fschulze,

Thanks for your PR. It definitely makes the plugin more sophisticated. Before I can merge this, it needs tests for the new features. Would you like to take care of that?

-Leah

**Comment by fschulze** [comment]
There you go.

**Comment by klrmn** [comment]
Thanks @fschulze!

I expect to release shortly. Just need to get it to work with py.test 2.2.x first (and I am fairly sure I have a handle on how to do that).

-Leah

**Comment by fschulze** [comment]
Thanks. What's the problem with 2.2.x?

**Comment by klrmn** [comment]
at first re was throwing errors (because it needed a particular version of
py, we didn't have py listed as a prereq, and pytest was loading an older
version)

then i realized that 2.2.x doesn't support fixtures =)

**Comment by klrmn** [comment]
@fschulze ,

I have released version 0.02 with your changes.

-Leah

**Pull request merged**
